version: '3.5'

services:

  namesrv:
    container_name: rocketmq-namesrv
    image: apache/rocketmq:latest
    environment:
      JAVA_OPT_EXT: -server -Xms256m -Xmx256m -Xmn256m
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-./volumes}/logs:/home/rocketmq/logs
    ports:
      - "127.0.0.1:9876:9876"
    command: sh ./mqnamesrv

  broker:
    container_name: rocketmq-broker
    image: apache/rocketmq:latest
    environment:
      NAMESRV_ADDR: namesrv:9876
      JAVA_OPT_EXT: -server -Xms512m -Xmx512m -Xmn256m
      BROKER_CONF: |
        brokerClusterName = MinimalCluster
        brokerName = broker-a
        brokerId = 0
        deleteWhen = 04
        fileReservedTime = 48
        brokerRole = ASYNC_MASTER
        flushDiskType = ASYNC_FLUSH
        brokerIP1=172.24.0.4
        grpcServerPort=8081
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-./volumes}/logs:/home/rocketmq/logs
      - ${DOCKER_VOLUME_DIRECTORY:-./volumes}/store:/home/rocketmq/store
    ports:
      # Dashboard pass through
      - 10909:10909
      - 10911:10911
      - 10912:10912
    command: |
      bash -c '
      mkdir -p /home/rocketmq/conf && 
      echo "$$BROKER_CONF" > /home/rocketmq/conf/broker.conf && 
      ./mqbroker -c /home/rocketmq/conf/broker.conf --enable-proxy 
      '

  dashboard:
    container_name: rocketmq-dashboard
    image: apacherocketmq/rocketmq-dashboard:latest
    # Access broker with localhost, port 8080 exposed in broker service
    ports:
      # Dashboard pass through
      - 8080:8080
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=namesrv:9876
