version: "3"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    env_file: env/.env
    volumes:
    - ./data/logs:/home/nacos/logs
    - ./data/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
    - "8848:8848"
    - "9555:9555"
    networks:
      - my-net
networks:
  my-net:
    external: true # 来自外部
