version: '3'

services:
  redis:
    image: redis:3
    container_name: "redis"
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    networks:
      - "redisnet"
networks:
  redisnet:
    driver: bridge
